#!/system/bin/sh

# I/O Shed.
echo "noop [row]" > /sys/block/mmcblk0/queue/scheduler

BML=`ls -d /sys/block/bml*`;
MMC=`ls -d /sys/block/mmc*`;
# I/O scheduler
for i in $BML $MMC; do
    if [ -e $i/queue/rotational ];
    then
        echo "0" > $i/queue/rotational;
    fi;
    if [ -e $i/queue/nr_requests ];
    then
        echo "8192" > $i/queue/nr_requests;
    fi;

    if [ -e $i/queue/iostats ];
    then
        echo "0" > $i/queue/iostats;
    fi;

    if [ -e $i/queue/read_ahead_kb ];
    then
        echo "512" > $i/queue/read_ahead_kb;
    fi;
done;

